spring.application.name=library-management-system

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

app.admin.email=${ADMIN_EMAIL:test@test.com}
app.admin.password=${ADMIN_PASSWORD:test}

spring.jpa.hibernate.ddl-auto=update

open.library.base-url=https://openlibrary.org
open.library.cover-base-url=https://covers.openlibrary.org/b/id/
open.library.search-limit=20

management.endpoints.web.exposure.include=health,info